### ISSUE TITLE
[Logging] log.info does not produce any output if executed in boot

### ISSUE THREAD

**Issue by danielegallingani** [buildo/ingredients#18]
Example: https://github.com/buildo/hailadoc/blob/api-988-notifications-add-synchronous-notifications/api/src/main/scala/hailadoc/launchers/Boot.scala#L74

**Comment by utaal** [comment]
Please change https://github.com/buildo/hailadoc/blob/api-988-notifications-add-synchronous-notifications/api/src/main/scala/hailadoc/launchers/Boot.scala#L54 to `private val log = logger("hailadoc.Boot")`

**Comment by danielegallingani** [comment]
woops, indeed line 60 was explanatory enough :)
